# Generated by Django 3.1.5 on 2021-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='ism')),
                ('l_name', models.CharField(max_length=100, verbose_name='familiya')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('subject', models.CharField(max_length=100, verbose_name='mavzu')),
                ('message', models.TextField(max_length=100, verbose_name='matn')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
    ]
