# Generated by Django 3.1.3 on 2020-12-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Korildi'),
        ),
    ]
