# Generated by Django 3.1.3 on 2020-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Reyting', 'verbose_name_plural': 'Reytinglar'},
        ),
        migrations.AddField(
            model_name='movie',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Yoqmadi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Yoqdi'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(blank=True, max_length=15, verbose_name='IP manzil'),
        ),
    ]
