# Generated by Django 3.2.4 on 2021-06-07 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210607_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(default=datetime.datetime(2021, 6, 7, 9, 33, 20, 538356, tzinfo=utc), max_length=100, verbose_name='You tube link'),
            preserve_default=False,
        ),
    ]
