# Generated by Django 3.2.4 on 2021-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_trailer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Post Tag name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Maqola Tegi',
                'verbose_name_plural': 'Maqolalar Teglari',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='movie.Tags'),
        ),
    ]
