# Generated by Django 3.1.5 on 2021-01-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201205_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Yoqmadi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Yoqdi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Korildi'),
        ),
    ]
