# Generated by Django 3.1.5 on 2021-01-23 03:35

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0005_auto_20210120_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2021, 1, 23, 3, 35, 24, 563539, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie/', verbose_name='Poster, Home=1300x500, default=182x268'),
        ),
    ]
