# Generated by Django 3.1.5 on 2021-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20210123_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='home_poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie/', verbose_name='Bosh sahifa posteri'),
        ),
    ]
